### ISSUE TITLE
New data structure —— List

### ISSUE THREAD

**Issue by qishenonly** [ByteStorage/FlyDB#137]
We need a new data structure, List, to extend the database's key-value storage structure.
We need to build some instructions into List to make it more complete.
If you are interested in extending the List data structure, you can comment below on the issue id you would like to try and we will assign it to you.

<html>
<body>
<!DOCTYPE html>

ID  | Method | Command | Description | Progress | People
-- | -- | -- | -- | -- | --
1 | LPush | LPush key value1 | Insert one or more values at the left of a list | finished  |  @SandTripper
2 | LPushs | LPushs key value1 value2 ... | Insert multiple values at the left of a list | finished  |  @SandTripper
3 | RPush | RPush key value1 | Insert one or more values at the right of a list | finished  |  @SandTripper
4 | RPushs | RPushs key value1 value2 ... | Insert multiple values at the right of a list | finished  |  @SandTripper
5 | LPop | LPop key | Remove and return the first value from the left of a list | finished  |  @SandTripper
6 | RPop | RPop key | Remove and return the last value from the right of a list | finished  |  @SandTripper
7 | LRange | LRange key start stop | Get a range of values from a list |  finished |  @SandTripper
8 | LLen | LLen key | Get the length of a list | finished  |  @SandTripper
9 | LRem | LRem key count value | Remove matching values from a list | finished  |  @SandTripper
10 | LSet | LSet key index value | Set the value at a specific index in a list | finished  |  @SandTripper
11 | LTrim | LTrim key start stop | Trim a list to the specified range of elements |finished   |  @SandTripper
12 | LIndex | LIndex key index | Get the element at a specific index in a list |  finished |  @SandTripper
13 | RPOPLPUSH | RPOPLPUSH source destination | Remove an element from the end of one list and push it to another list | finished |  @SandTripper

</body>
</html>

**Comment by SandTripper** [comment]
I want to receive tasks from ID1 to 13
