### ISSUE TITLE
New data structure —— Set

### ISSUE THREAD

**Issue by qishenonly** [ByteStorage/FlyDB#138]
We need a new data structure, Set, to extend the database's key-value storage structure.
We need to build some instructions into Set to make it more complete.
If you are interested in extending the Set data structure, you can comment below on the issue id you would like to try and we will assign it to you.
<html>
<body>
<!DOCTYPE html>

ID | Method | Command | Description | People | Progress
-- | -- | -- | -- | -- | --
1 | SAdd | SAdd key member | Add a member to a set |   |  
2 | SAdds | SAdds key member1 member2 ... | Add multiple members to a set |   |  
3 | SRem | SRem key member1 | Remove a member from a set |   |  
4 | SRems | SRems key member1 member2 ... | Remove multiple members from a set |   |  
5 | SCard | SCard key | Get the cardinality (size) of a set |   |  
6 | SMembers | SMembers key | Get all members of a set |   |  
7 | SIsMember | SIsMember key member | Check if a member exists in a set |   |  
8 | SUnion | SUnion key1 key2 | Get the union of multiple sets |   |  
9 | SInter | SInter key1 key2 | Get the intersection of multiple sets |   |  
10 | SDiff | SDiff key1 key2 | Get the difference between two sets |   |  
11 | SUnionStore | SUnionStore destination key1 key2 | Store the union of multiple sets in a destination set |   |  
12 | SInterStore | SInterStore destination key1 key2 | Store the intersection of multiple sets in a destination set

</body>
</html>

**Comment by sjcsjc123** [comment]
let me try it

**Comment by saeid-a** [comment]
I want to take this issue.

**Comment by qishenonly** [comment]
Sure, you can try it. You can refine the methods supported by the `Set` data structure as much as possible without limiting yourself to the commands listed.
