### ISSUE TITLE
New data structure —— ZSet 

### ISSUE THREAD

**Issue by qishenonly** [ByteStorage/FlyDB#139]
We need a new data structure, ZSet , to extend the database's key-value storage structure.
We need to build some instructions into ZSet to make it more complete.
If you are interested in extending the ZSet data structure, you can comment below on the issue id you would like to try and we will assign it to you.
<html>
<body>
<!DOCTYPE html>

ID  | Method | Command | Description | Progress | People
-- | -- | -- | -- | -- | --
1 | ZAdd | ZAdd key score member | Add a single member with its score to a sorted set |   |  
2 | ZAdds | ZAdd key score1 member1 ... | Add multiple members with their scores to a sorted set |   |  
3 | ZRem | ZRem key member | Remove a single member from a sorted set |   |  
4 | ZRems | ZRem key member1 ... | Remove multiple members from a sorted set |   |  
3 | ZScore | ZScore key member | Get the score of a member in a sorted set |   |  
4 | ZRank | ZRank key member | Get the rank of a member in a sorted set |   |  
5 | ZRevRank | ZRevRank key member | Get the reverse rank of a member in a sorted set |   |  
6 | ZRange | ZRange key start stop [WITHSCORES] | Get members in a specified range from a sorted set |   |  
7 | ZRevRange | ZRevRange key start stop [WITHSCORES] | Get members in a specified range from a sorted set in reverse order |   |  
8 | ZCount | ZCount key min max | Count the number of members in a sorted set within a given range |   |  
9 | ZCard | ZCard key | Get the number of members in a sorted set |   |  
10 | ZIncrBy | ZIncrBy key increment member | Increment the score of a member in a sorted set by a given increment

</body>
</html>

**Comment by saeid-a** [comment]
I want to take this issue.

**Comment by qishenonly** [comment]
Sure, you can try it. You can refine the methods supported by the `ZSet` data structure as much as possible without limiting yourself to the commands listed.
