### ISSUE TITLE
New data structure —— BitMap 

### ISSUE THREAD

**Issue by qishenonly** [ByteStorage/FlyDB#140]
We need a new data structure, BitMap , to extend the database's key-value storage structure.
We need to build some instructions into BitMap to make it more complete.
If you are interested in extending the BitMap data structure, you can comment below on the issue id you would like to try and we will assign it to you.

<html>
<body>
<!DOCTYPE html>

ID  | Method | Command | Description | Progress | People
-- | -- | -- | -- | -- | --
1 | SetBit | SetBit key offset value | Set the bit at the specified offset in the bitmap to the specified value |   |  
2 | SetBits | SetBits key offset value1 ... | Set a group of bits at the specified offsets in the bitmap to the specified values |   |  
3 | GetBit | GetBit key offset | Get the value of the bit at the specified offset in the bitmap |   |  
4 | GetBits | GetBits key offset1 ... | Get the values of a group of bits at the specified offsets in the bitmap |   |  
5 | BitCount | BitCount key [start end] | Count the number of bits set to 1 in the specified range of the bitmap |   |  
6 | BitOp | BitOp operation destkey key1 [key2 ...] | Perform the specified logical operation on one or more bitmaps and save the result to the destination bitmap |   |  
7 | BitDel | BitDel key offset | Delete the bit at the specified offset in the bitmap |   |  
8 | BitDels | BitDels key offset1 ... | Delete a group of bits at the specified offsets in the bitmap

</body>
</html>

**Comment by SandTripper** [comment]
I want to receive tasks from ID1 to 8, and I wanna what is the 'operation' in ID6

**Comment by qishenonly** [comment]
> I want to receive tasks from ID1 to 8, and I wanna what is the 'operation' in ID6

ok，try to do it.
As for your question on issue 6, let me give you a general answer:

In a BitOp command, "operation" refers to a logical operation to be performed on one or more bitmaps. The operation can be one of four:

`AND`: logical bit and operation: performs logical operations on the corresponding bits of multiple bitmap.
`OR`: logical bit or operation that performs logic or operations on the corresponding bits of multiple bitmaps.
`XOR`: Performs the logical XOR operation on the corresponding bits of multiple bitmaps.
`NOT`: Performs the logical reverse operation on each bit of a bitmap.

By specifying different operations in the BitOp command, it is possible to perform different types of logical operations on the bitmap and save the results to the specified destination bitmap. For example,  perform logic and operations on multiple bitmaps and save the results to a new bitmap, thus achieving intersection operations on multiple bitmaps.

Bitmap development is a bit difficult, come on, try to work hard to solve it.

**Comment by SandTripper** [comment]
> > I want to receive tasks from ID1 to 8, and I wanna what is the 'operation' in ID6
> 
> ok，try to do it. As for your question on issue 6, let me give you a general answer:
> 
> In a BitOp command, "operation" refers to a logical operation to be performed on one or more bitmaps. The operation can be one of four:
> 
> `AND`: logical bit and operation: performs logical operations on the corresponding bits of multiple bitmap. `OR`: logical bit or operation that performs logic or operations on the corresponding bits of multiple bitmaps. `XOR`: Performs the logical XOR operation on the corresponding bits of multiple bitmaps. `NOT`: Performs the logical reverse operation on each bit of a bitmap.
> 
> By specifying different operations in the BitOp command, it is possible to perform different types of logical operations on the bitmap and save the results to the specified destination bitmap. For example, perform logic and operations on multiple bitmaps and save the results to a new bitmap, thus achieving intersection operations on multiple bitmaps.
> 
> Bitmap development is a bit difficult, come on, try to work hard to solve it.

Thanks for your answer, I understand the requirement, I think I can handle it.

**Comment by qishenonly** [comment]
> > > I want to receive tasks from ID1 to 8, and I wanna what is the 'operation' in ID6
> > 
> > 
> > ok，try to do it. As for your question on issue 6, let me give you a general answer:
> > In a BitOp command, "operation" refers to a logical operation to be performed on one or more bitmaps. The operation can be one of four:
> > `AND`: logical bit and operation: performs logical operations on the corresponding bits of multiple bitmap. `OR`: logical bit or operation that performs logic or operations on the corresponding bits of multiple bitmaps. `XOR`: Performs the logical XOR operation on the corresponding bits of multiple bitmaps. `NOT`: Performs the logical reverse operation on each bit of a bitmap.
> > By specifying different operations in the BitOp command, it is possible to perform different types of logical operations on the bitmap and save the results to the specified destination bitmap. For example, perform logic and operations on multiple bitmaps and save the results to a new bitmap, thus achieving intersection operations on multiple bitmaps.
> > Bitmap development is a bit difficult, come on, try to work hard to solve it.
> 
> Thanks for your answer, I understand the requirement, I think I can handle it.

have a try.

**Comment by SandTripper** [comment]
Can you give an example of calling ID2，I don't quite understand what ’a group of bits‘ means

**Comment by SandTripper** [comment]
There is another question, when the ”BitDel key offset“ is executed, whether the bit after the offset should be moved forward by one bit？

**Comment by qishenonly** [comment]
> Can you give an example of calling ID2，I don't quite understand what ’a group of bits‘ means

Thank you for your question, I will answer your question.

An operation with ID 2 is actually a batch of operations with ID 1 (multiple values at once). `SetBit `is used to set the value of a single bit. `SetBits `is used to set the value of a group of bits.

Here is an example of `SetBits`:
`SETBITS mybitmap 0 1 2 1 4 0`

In our example, we set a set of bits at the locations of the bitmap with offsets of 0, 2, and 4. Bits with offsets 0 and 2 are set to 1, and bits with offsets 4 are set to 0.

I'll be happy to answer your questions. Please feel free to let us know if you have any further questions.

**Comment by SandTripper** [comment]
Thanks, there is another question, when the ”BitDel key offset“ is executed, whether the bit after the offset should be moved forward by one bit？

**Comment by qishenonly** [comment]
> There is another question, when the ”BitDel key offset“ is executed, whether the bit after the offset should be moved forward by one bit？

It's my pleasure to continue answering your questions, so let me explain briefly.

When the `BitDel key offset` command is executed, the bits at the specified offset in the bitmap are usually deleted and the bits after the offset are moved forward one position to fill the gap left by the deleted bits.

For example, if you have a bitmap with a bit sequence of `11011010`, execute the `BitDel key 3` command, where the offset is 3.  This will remove the bits in the fourth position in the bitmap, the fourth position calculated from 0.  After this bit is deleted, the bitmap becomes `1101010`.

**Comment by SandTripper** [comment]
Very precise and understandable answer！

**Comment by qishenonly** [comment]
> Very precise and understandable answer！

Thank you for your feedback! I'm glad my answer was accurate and easy to understand. If you have any questions or need further assistance, please feel free to ask.

**Comment by saeid-a** [comment]
Hey, I was wondering, since some libraries already support such operations and bitsets in general, like [bitset](https://github.com/bits-and-blooms/bitset) and [bitmap](https://github.com/kelindar/bitmap), why don't we use them?

**Comment by qishenonly** [comment]
There are several reasons for not using existing libraries like `bitset `or `bitmap`:

1. Customization: Custom implementations allow us to customize functionality according to our project needs.
2. Integration: A custom implementation seamlessly integrates with the rest of our project, ensuring compatibility and reducing dependencies.

In the future, we will consider whether to replace the existing library through practical tests

**Comment by qishenonly** [comment]
> Hey, I was wondering, since some libraries already support such operations and bitsets in general, like [bitset](https://github.com/bits-and-blooms/bitset) and [bitmap](https://github.com/kelindar/bitmap), why don't we use them?

There are several reasons for not using existing libraries like `bitset `or `bitmap`:

1. Customization: Custom implementations allow us to customize functionality according to our project needs.
2. Integration: A custom implementation seamlessly integrates with the rest of our project, ensuring compatibility and reducing dependencies.

In the future, we will consider whether to replace the existing library through practical tests

**Comment by saeid-a** [comment]
#173

**Comment by qishenonly** [comment]
> #173

thanks
