### ISSUE TITLE
Refactoring the cli interface and implementing methods corresponding to the String data structure

### ISSUE THREAD

**Issue by qishenonly** [ByteStorage/FlyDB#147]
At present, the put, get, and del methods in the cli are all forced by string. These methods have limitations and cannot be connected to subsequent different data structures.
![image](https://github.com/ByteStorage/FlyDB/assets/90094807/88d380cf-5766-4466-8aab-cb9a323eea3c)
We need a unified interface now, and then implement these interfaces using these different kinds of data structures.
Now that the basic methods of the String data structure have been built, you need to complete the various methods in the String data structure in the cli.
See #135 for the method corresponding to the String data structure

**Comment by sjcsjc123** [comment]
it may can be closed?
