### ISSUE TITLE
add docker service for FlyDB

### ISSUE THREAD

**Issue by sjcsjc123** [ByteStorage/FlyDB#153]
In order to more easily access the k8s deployment in the future, it is necessary to add docker service to Flydb.

**Comment by saeid-a** [comment]
I can handle this issue.

**Comment by sjcsjc123** [comment]
Thanks, you can have a try!

**Comment by saeid-a** [comment]
Do we want to build binaries in the Dockerfile or the Makefile and COPY the binaries into the image?

**Comment by sjcsjc123** [comment]
We hope to build a `flydb-server` image and upload it to the Docker Hub, and we also hope to write a function that can pull the `flydb-server` image through the build library and run it locally by the user.

**Comment by sjcsjc123** [comment]
At present, it may be possible to write a Dockerfile first to build a `flydb-server` image.

**Comment by sjcsjc123** [comment]
I am very sorry, after internal discussions, we are preparing to open a new library responsible for Docker and Kubernetes deployment. If you are interested, you can submit the code to the [FlyDB-Cloud](https://github.com/ByteStorage/FlyDB-Cloud) library!

**Comment by saeid-a** [comment]
Sure, is there any changes that needs to be made or not?

**Comment by sjcsjc123** [comment]
Not yet.

**Comment by saeid-a** [comment]
I've submitted a pull request for the Dockerfile in the other repository. However, it would be more efficient if we built the docker image in this repository and uploaded the resulting image to Docker Hub using code integrated into our continuous integration (CI) process. This way, we can configure deployment files and settings for other cloud deployments in the [FlyDB-Cloud](https://github.com/ByteStorage/FlyDB-Cloud) repository.
[PR for this issue on FlyDB-Cloud](https://github.com/ByteStorage/FlyDB-Cloud/pull/1)

**Comment by sjcsjc123** [comment]
Yes! Perhaps we don't need to build an image in the `CI` in this repository. We can monitor the release of new versions of [FlyDB](https://github.com/ByteStorage/FlyDB) in the `CI` of the [FlyDB-Cloud](https://github.com/ByteStorage/FlyDB-Cloud) repository. When a new version is released, we can automatically build an image in the `CI` and upload it.
