### ISSUE TITLE
Build project static website

### ISSUE THREAD

**Issue by qishenonly** [ByteStorage/FlyDB#165]
# Problem Description:
Our open-source project requires a static website to showcase project information and provide developers with a platform to share and access relevant documentation. Currently, we do not have comprehensive project documentation, but we aim to build a preliminary static website structure and integrate the casual documentation provided by developers to create a platform for showcasing project information.

# Objective:

Our objective is to establish a basic static website structure and incorporate the casual documentation provided by developers into the website. Although the documentation content may be incomplete or temporarily inaccurate, we want to provide developers with a platform to browse the documentation and lay the foundation for further project development.

# Suggestions and Requirements:

1. Select a suitable static website generator or framework such as Jekyll, Hugo, Gatsby, etc. Consider factors like ease of use, extensibility, and community support.
2. Design and implement the overall website architecture, including page layout, navigation structure, and content organization.
3. Create a project homepage to present an overview, features, and important links related to the project.
4. Integrate the casual documentation provided by developers and convert it into Markdown format, organizing it appropriately.
5. Design and implement a template for documentation pages to showcase the casual documentation provided by developers. Use elements like table of contents, sections, and headings to enhance the readability of the documentation.
6. Consider adding a search functionality to enable developers to quickly search and browse the documentation.
7. Ensure a responsive design for the website to ensure proper display on different devices and provide a seamless user experience.
8. Configure and deploy the website to a suitable hosting platform such as GitHub Pages, Netlify, Vercel, etc.

# Expected Deliverables:

The completed static website should have the following features:

- A clean and concise page layout and navigation structure for easy browsing and access to documentation by developers.
- Integration of the casual documentation provided by developers and organized in a suitable structure for developers to access.
- Responsive design to adapt to different devices and screen sizes, providing a pleasant user experience.
- Successful deployment to a suitable hosting platform, ensuring the website is accessible online.

**Comment by sjcsjc123** [comment]
good issue!

**Comment by lim-yoona** [comment]
I have an idea that I can complete a static website similar to my blog as a FlyDB's website. 

It is based on the Jekyll theme, and its comment system is implemented using Valine, and it is deployed on GitHub Pages. You only need to upload the file in Markdown format to the _posts folder of the corresponding repositories, and the document can be displayed on the website. The article includes the table of contents and title. This blog system also has its own search function, which can search for related documents. Classification of documents can be achieved by adding tags in Markdown files. 

You can go to my blog address to see the effect: https://ymiir.top

**Comment by lim-yoona** [comment]
> I have an idea that I can complete a static website similar to my blog as a FlyDB's website.
> 
> It is based on the Jekyll theme, and its comment system is implemented using Valine, and it is deployed on GitHub Pages. You only need to upload the file in Markdown format to the _posts folder of the corresponding repositories, and the document can be displayed on the website. The article includes the table of contents and title. This blog system also has its own search function, which can search for related documents. Classification of documents can be achieved by adding tags in Markdown files.
> 
> You can go to my blog address to see the effect: https://ymiir.top

Developers can submit new documents by pr, which can be displayed on the website after merging.

**Comment by qishenonly** [comment]
Thank you for your recommendation. After discussion by our core team, your blog series style is not appropriate as an official website for the community. You can refer to the [openIM open source community](https://www.rentsoft.cn/) or [Vue's official website](https://cn.vuejs.org/), and try to build a website in their form. He may have a large amount of work, but he only needs to build the basic architecture and pages in the early stage.

**Comment by sjcsjc123** [comment]
> Thank you for your recommendation. After discussion by our core team, your blog series style is not appropriate as an official website for the community. You can refer to the [openIM open source community](https://www.rentsoft.cn/) or [Vue's official website](https://cn.vuejs.org/), and try to build a website in their form. He may have a large amount of work, but he only needs to build the basic architecture and pages in the early stage.

it like difficult, may be http://sealer.cool/ and https://cubefs.io/ are better. We just need `Doc` and `Blog`.
