### ISSUE TITLE
feat: determine the appropriate default configuration

### ISSUE THREAD

**Issue by sjcsjc123** [ByteStorage/FlyDB#175]
We need to determine the appropriate default configuration for the raft cluster.
![image](https://github.com/ByteStorage/FlyDB/assets/88550136/029b30b6-edcf-4847-a003-3c904125bf57)

**Comment by saeid-a** [comment]
I want to take this issue.

**Comment by sjcsjc123** [comment]
thanks!

**Comment by saeid-a** [comment]
#185
