### ISSUE TITLE
Rewrite the LogStore component of raft

### ISSUE THREAD

**Issue by sjcsjc123** [ByteStorage/FlyDB#177]
For the purpose of each interface, you can refer to the internal definition of `hashicorp/raft`, or refer to some existing implementation methods defined within `hashicorp/raft`.
```go
// raftLog implements raft.LogStore interface, we can use it to store raft logs
// how to store raft logs? we can use FlyDB/RocksDB/LevelDB/BoltDB to store raft logs
// maybe we can use FlyDB
type raftLog struct {
	// implement me
}

// newRaftLog returns a new raftLog
func newRaftLog() raft.LogStore {
	return &raftLog{}
}

func (r *raftLog) FirstIndex() (uint64, error) {
	//TODO implement me
	panic("implement me")
}

func (r *raftLog) LastIndex() (uint64, error) {
	//TODO implement me
	panic("implement me")
}

func (r *raftLog) GetLog(index uint64, log *raft.Log) error {
	//TODO implement me
	panic("implement me")
}

func (r *raftLog) StoreLog(log *raft.Log) error {
	//TODO implement me
	panic("implement me")
}

func (r *raftLog) StoreLogs(logs []*raft.Log) error {
	//TODO implement me
	panic("implement me")
}

func (r *raftLog) DeleteRange(min, max uint64) error {
	//TODO implement me
	panic("implement me")
}
```

**Comment by saeid-a** [comment]
It would be great if we could customize the underlying storage for the `newRaftLog` function by providing the `config` as input or any other relevant input. This will allow us to create a convenient solution for now while enabling us to add more storage options in the future, as required.

**Comment by sjcsjc123** [comment]
It is indeed a good method. We can add user-defined `raft log storage` in the `cluster` structure, while the `newRaftLog` function uses the corresponding DB for log storage based on the user-defined settings. Your suggestion is very good!

**Comment by saeid-a** [comment]
#197

**Comment by saeid-a** [comment]
In order to incorporate support for `RocksDB`, we must include a library. Based on our research, it appears that [grocksdb](https://github.com/linxGnu/grocksdb) is the most developed option; however, it requires a compilation process that involves several steps that we must consider. Although I have already included three storage choices, implementing `RocksDB` support requires further examination of the library and maybe some guides on compilation and some changes to the `Dockerfile`.

**Comment by sjcsjc123** [comment]
Yes, the introduction of dependencies in `RocksDB` is indeed a hassle, and `RocksDB` does not provide go SDK. I have not been exposed to the [grocksdb](https://github.com/linxGnu/grocksdb) you mentioned. In my understanding, many places use `RocksDB` to store `LogStore`, such as [TiDB](https://github.com/pingcap/tidb). I have not seen the library you mentioned before. However, since both require the introduction of C++ dependencies, it is recommended to use the original `RocksDB` instead if using `Rocksdb`. Rocksdb rewritten by the Go language may not perform as well as C++. What do you think? You can share your opinion?

**Comment by sjcsjc123** [comment]
Of course, we also hope that our project is a pure go language, and we do not want users to manually configure the C++ related environment to use our project. We may consider using the library you mentioned.

**Comment by saeid-a** [comment]
@sjcsjc123  It seems that [seaweedfs](https://github.com/seaweedfs/seaweedfs) also utilizes the [grocksdb](https://github.com/linxGnu/grocksdb) library. To use this library, the only requirement is to have the `RocksDB` library installed. However, I have taken the initiative to write the `RocksDB` integration and can push it to the PR for testing purposes.

**Comment by saeid-a** [comment]
@sjcsjc123, and before merging the `PR,` please let me squash all the commits first.

**Comment by sjcsjc123** [comment]
Can you tell us your commonly used chat application and provide us with a contact information? We can discuss it in detail privately with another member of the community!
