### ISSUE TITLE
The function expire with a little bug in structure/string.go 

### ISSUE THREAD

**Issue by wangchenguang123** [ByteStorage/FlyDB#209]
some bug in this picture
![ad8a5eabff9ed1b68bb399ce6432f0c](https://github.com/ByteStorage/FlyDB/assets/56055887/ca499a8e-f311-440a-b67e-535a9ee05c84)
when set key value both string 
set key expire test failed

**Comment by qishenonly** [comment]
Thanks for bringing up the bug, I've already fixed it. #211
