### ISSUE TITLE
cli supports `hash` data structures

### ISSUE THREAD

**Issue by qishenonly** [ByteStorage/FlyDB#214]

**Comment by qishenonly** [comment]
Currently, only the `HSet`, `HGet`, and `HDel` commands are supported.

**Comment by wangchenguang123** [comment]
i will try to finish some functions

**Comment by sjcsjc123** [comment]
try to do it!

**Comment by sjcsjc123** [comment]
Has it been fully implemented?

**Comment by wangchenguang123** [comment]
> Has it been fully implemented?

i have finished all functions in this picture
![图片](https://github.com/ByteStorage/FlyDB/assets/56055887/f5cbf163-d88e-4c32-b224-b2d45cc84f64)
