### ISSUE TITLE
Make the logo more three-dimensional

### ISSUE THREAD

**Issue by sjcsjc123** [ByteStorage/FlyDB#228]
![image](https://github.com/ByteStorage/FlyDB/assets/88550136/4950eb19-b968-43d5-8c4c-18a3a1e1e3ac)
Refer to this to make the loading interface more cool

**Comment by halalala222** [comment]
![image](https://github.com/user-attachments/assets/53d7112f-a788-4527-aad9-f04b178c1152)
I believe this issue has already been completed but it has not been closed.

**Comment by qishenonly** [comment]
thanks
