### ISSUE TITLE
bug: File empty value problem caused by `mmap IO`

### ISSUE THREAD

**Issue by qishenonly** [ByteStorage/FlyDB#232]
As shown in the following figure, using `mmap` can result in a large number of empty values in the file, which needs to be resolved quickly.But that doesn't happen with `fileio`.

![image](https://github.com/ByteStorage/FlyDB/assets/90094807/3f393a59-fa75-414c-bfec-185a9087ea17)

![image](https://github.com/ByteStorage/FlyDB/assets/90094807/8ab4513d-7529-4b7c-bccc-70855cb70f69)
![image](https://github.com/ByteStorage/FlyDB/assets/90094807/62771353-9bd2-4910-829b-87003101423a)

**Comment by ZhaoShuaiUp** [comment]
Beacause you didn't call db.close() function

**Comment by qishenonly** [comment]
All right, that's my problem.
