### ISSUE TITLE
string structure has some bug in function append 

### ISSUE THREAD

**Issue by wangchenguang123** [ByteStorage/FlyDB#241]
![86df3bc815d416551882d41f537de5c](https://github.com/ByteStorage/FlyDB/assets/56055887/4362153e-3fa1-40ac-87d3-d04f9971e9b4)
![51bbbfd7ed449b9e62ac1d948f83285](https://github.com/ByteStorage/FlyDB/assets/56055887/a4e1e479-c343-4f2e-99bd-c13c75125e8b)

**Comment by qishenonly** [comment]
#243 
![image](https://github.com/ByteStorage/FlyDB/assets/90094807/918d91be-1ae4-4961-9806-19ffc9a83f63)
