### ISSUE TITLE
list structure Rpop

### ISSUE THREAD

**Issue by wangchenguang123** [ByteStorage/FlyDB#242]

**Comment by wangchenguang123** [comment]
![99a7455158507e8e7dee924ef1bead5](https://github.com/ByteStorage/FlyDB/assets/56055887/03ad23c8-3c03-48ac-8a37-225776801061)
![eaed31891541eabc5ff3f38e7b6d5a1](https://github.com/ByteStorage/FlyDB/assets/56055887/251f3b86-81b8-4b13-83d4-43197109348a)

**Comment by SandTripper** [comment]
#244
