### ISSUE TITLE
implement the `MkDir` interface

### ISSUE THREAD

**Issue by sjcsjc123** [ByteStorage/flydb#45]
![image](https://github.com/qishenonly/flydb/assets/88550136/088023bc-0dba-4caf-8925-2edc1b71d269)

**Comment by bigboss2063** [comment]
I can help with this.

**Comment by sjcsjc123** [comment]
This issue needs to find the optimal structure of the directory tree. Can you do that? The current directory tree structure may not be optimal.

**Comment by bigboss2063** [comment]
Currently, I have implemented a version of **MkDir** based on the provided data structure. I am now looking for ways to optimize this directory tree. Would you mind reviewing it and providing some advice?

**Comment by bigboss2063** [comment]
Perhaps considering the use of a hashtable instead of a slice to store child nodes could be a more efficient approach？

**Comment by sjcsjc123** [comment]
You can try it out and write unit tests to test different data structures. Unit tests should ideally include cases that test the insertion or reading of tens of thousands of pieces of data. I will review this

**Comment by bigboss2063** [comment]
Alright, thanks.
