### ISSUE TITLE
fix bug with bufio

### ISSUE THREAD

**Issue by sjcsjc123** [ByteStorage/flydb#73]
![image](https://github.com/ByteStorage/flydb/assets/88550136/936e1333-a288-4529-88e2-9c2214de1e96)
this test run fail, please fix it

**Comment by sjcsjc123** [comment]
![image](https://github.com/ByteStorage/flydb/assets/88550136/8f00f930-1062-4aa3-a0c7-7006c1961563)
this test run fail, too

**Comment by bigboss2063** [comment]
I suspect that the issue may be related to the `Bufio.Read` function not flushing the data in the buffer before reading, which resulted in the failure of the two test cases.

**Comment by sjcsjc123** [comment]
you can try it out.
