### ISSUE TITLE
Add http server

### ISSUE THREAD

**Issue by qishenonly** [ByteStorage/FlyDB#79]
FlyDB needs to add a http service.

**Comment by CrazyJius** [comment]
At present, only the put method for HTTP services is written by a contributor. Due to being inactive for a long time, if you feel that you can complete the support for HTTP services, you can rewrite this part of the code.

**Comment by qishenonly** [comment]
At present, only the put method for HTTP services is written by a contributor. Due to being inactive for a long time, if you feel that you can complete the support for HTTP services, you can rewrite this part of the code.

**Comment by wangchenguang123** [comment]
想问一下，这个是往这个文件里补充功能嘛，例如post，download下载文件这类的？

**Comment by qishenonly** [comment]
> 想问一下，这个是往这个文件里补充功能嘛，例如post，download下载文件这类的？

完善http服务，集成http协议的请求方式对接db的api，例如get，put，delete，getlistkey等。
问下download下载文件的想法？

**Comment by wangchenguang123** [comment]
> 完善http服务，集成http协议的请求方式对接db的api，例如get，put，delete，getlistkey等。
> 问下download下载文件的想法？

这个下载文件可能我想的比较简单，就是可能有些用户存储的是一个文件路径，有这个下载的需求。

**Comment by qishenonly** [comment]
> > 完善http服务，集成http协议的请求方式对接db的api，例如get，put，delete，getlistkey等。
> > 问下download下载文件的想法？
> 
> 这个下载文件可能我想的比较简单，就是可能有些用户存储的是一个文件路径，有这个下载的需求。

暂时不用，有需求时再安排

**Comment by wangchenguang123** [comment]
> > > 完善http服务，集成http协议的请求方式对接db的api，例如get，put，delete，getlistkey等。
> > > 问下download下载文件的想法？
> > 
> > 
> > 这个下载文件可能我想的比较简单，就是可能有些用户存储的是一个文件路径，有这个下载的需求。
> 
> 暂时不用，有需求时再安排

那我再想想能加上点啥方法和DB对接
