### ISSUE TITLE
implement `AssignData`

### ISSUE THREAD

**Issue by sjcsjc123** [ByteStorage/FlyDB#81]
![image](https://github.com/ByteStorage/flydb/assets/88550136/88ebc168-0485-470c-9870-2b9cfc0f1940)
This method requires cutting the data into several parts and then having a map. Just use reedsolomon api.

**Comment by wangchenguang123** [comment]
i want to try it

**Comment by qishenonly** [comment]
> i want to try it

ok, hava a try

**Comment by sjcsjc123** [comment]
You can reopen pull request. There is a bug with `client_test`, i have fix it.
