### ISSUE TITLE
Data backup

### ISSUE THREAD

**Issue by qishenonly** [ByteStorage/FlyDB#96]
In order to avoid serious problems such as data directory failure or data file corruption resulting in data loss, we need to perfect a data backup function for FlyDB.

**Comment by Uncle-Justice** [comment]
do you mean backup like RDB and AOF in redis?

**Comment by qishenonly** [comment]
> do you mean backup like RDB and AOF in redis?

Due to disparities in storage engines, FlyDB is not well-suited for RDB and AOF backup methods. Our data backup requirements are relatively straightforward: we simply copy the data directory to an alternate location. In the event of damage to the original directory, we can reload the data from the copied directory to ensure data integrity.

**Comment by Uncle-Justice** [comment]
i wanna try this. 

here is my plan:
1. add backup dir conf in DefaultOptions
2. add func backup/restore in db.go. mutex on, then copy active/older/hint files to backup dir

should i set default backup dir in tempdir too? or some other fixed dir?

**Comment by qishenonly** [comment]
Your plan appears to be promising, yet a few key points require clarification and elaboration.

- The strategic inclusion of a backup directory configuration within DefaultOptions is a commendable initiative. This step empowers users by allowing them to explicitly designate the storage location for backup data.
- During the backup process, it's imperative to copy both active, old, and hint files to the backup directory to ensure the integrity of the backup. For the recovery process, careful consideration must be given to how to manage the files post-restoration to avert any inconsistencies in the data files.
- Compress backup data to reduce the size of backup files, saving storage space and transfer time.  You can use standard data compression algorithms such as Gzip
- Automatically back up your data regularly, say once a week?
- The default backup directory should be selected based on usage and user needs. Tempdir is suitable for one-time backup or testing, while setting it as a fixed directory is more suitable for production environments because it can alleviate the vulnerability of unintentional data deletion.

**Comment by qishenonly** [comment]
#302
