### ISSUE TITLE
New memory index —— HashMap

### ISSUE THREAD

**Issue by qishenonly** [ByteStorage/FlyDB#99]
We need a new in-memory index, HashMap, to allow users to choose the index that is more efficient for the business during development.

**Comment by lim-yoona** [comment]
May I try this issue?

**Comment by qishenonly** [comment]
> May I try this issue?我可以试试这个问题吗？

OK，try to do it.

**Comment by qishenonly** [comment]
What is the minimum version of go required for the third-party library of hashmap you are using?

**Comment by lim-yoona** [comment]
> What is the minimum version of go required for the third-party library of hashmap you are using?

The minimal supported Golang version is 1.19 as it makes use of Generics and the new atomic package helpers.

**Comment by qishenonly** [comment]
![image](https://github.com/ByteStorage/FlyDB/assets/90094807/3a2a4e75-c3ea-47c7-8b81-ba95fa406abc)
Hashmap memory index is having problems running TestPutAndGet tests, waiting for no result. Consider fixing this problem and testing the performance of hashmap.

**Comment by lim-yoona** [comment]
> ![image](https://user-images.githubusercontent.com/90094807/251392700-3a2a4e75-c3ea-47c7-8b81-ba95fa406abc.png) Hashmap memory index is having problems running TestPutAndGet tests, waiting for no result. Consider fixing this problem and testing the performance of hashmap.

OK, I will try.

**Comment by qishenonly** [comment]
> ![image](https://user-images.githubusercontent.com/90094807/251392700-3a2a4e75-c3ea-47c7-8b81-ba95fa406abc.png) Hashmap memory index is having problems running TestPutAndGet tests, waiting for no result. Consider fixing this problem and testing the performance of hashmap.Hashmap

**Comment by qishenonly** [comment]
> > ![image](https://user-images.githubusercontent.com/90094807/251392700-3a2a4e75-c3ea-47c7-8b81-ba95fa406abc.png) Hashmap memory index is having problems running TestPutAndGet tests, waiting for no result. Consider fixing this problem and testing the performance of hashmap.
> 
> OK, I will try.

I'll comment your hashmap test code first to avoid further development by our development team. A problem with the iterator for Hashmap prevents the test method TestPutAndGet from testing performance.
